export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const ADD_CART_ACTION_CLICK = "ADD_CART_ACTION_CLICK";
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";
